# Generated by Django 5.0.6 on 2024-05-26 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='min_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
