# Generated by Django 5.0.6 on 2024-05-26 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_stat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
