# Generated by Django 5.0.6 on 2024-05-26 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_stat'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Stat Summary',
                'verbose_name_plural': 'Stats Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('main.stat',),
        ),
    ]
